Repository OpenLightingProject/open-fixture-library, pull requests merged in 2020-04, with the labels that each got.

#1262 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#1260 API Refactoring
  cli/import-fixture.js
  docs/ui.md
  lib/create-github-pr.js
  lib/get-out-object-from-editor-data.js
  lib/site-crawler.js
  lib/types.js
  main.js
  package-lock.json
  package.json
  ui/ajax/import-fixture-file.js
  ui/ajax/submit-editor.js
  ui/api/fixtures/from-editor.js
  ui/api/fixtures/import.js
  ui/api/fixtures/submit.js
  ui/api/get-search-results.js
  ui/api/index.js
  ui/api/submit-feedback.js
  ui/assets/scripts/editor-utils.js
  ui/components/HelpWantedDialog.vue
  ui/components/editor/EditorSubmitDialog.vue
  ui/components/fixture-page/FixturePage.vue
  ui/pages/_manufacturerKey/_fixtureKey.vue
  ui/pages/fixture-editor.vue
  ui/pages/import-fixture-file.vue
  ui/pages/search.vue
Labels: component-editor, component-ui, refactoring

#1274 Fix typo safe/save
  docs/README.md
Labels: documentation

#1277 Add Note about broken Windows build
  docs/CONTRIBUTING.md
Labels: documentation

#1278 Fix SVG loader on Windows
  nuxt.config.js
Labels: bug, component-ui

#1279 Add Windows Install Instructions
  docs/CONTRIBUTING.md
Labels: documentation
