Repository OpenLightingProject/open-fixture-library, pull requests merged in 2021-11, with the labels that each got.

#2234 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#2246 Use top-level `await`
  .eslintrc.cjs
  cli/build-plugin-data.js
  cli/build-register.js
  cli/build-test-fixtures.js
  cli/diff-plugin-outputs.js
  cli/export-fixture.js
  cli/import-fixture.js
  cli/run-export-test.js
  docs/fixture-model.md
  tests/external-links.js
  tests/github/export-diff.js
  tests/github/exports-valid.js
  tests/github/schema-version-reminder.js
  tests/http-status.js
Labels: refactoring

#2249 Install `eslint-plugin-sonarjs` to make code more readable
  .eslintrc.cjs
  cli/diff-plugin-outputs.js
  cli/export-fixture.js
  cli/import-fixture.js
  cli/run-export-test.js
  lib/create-github-pr.js
  lib/fixture-json-stringify.js
  lib/get-ajv-error-messages.js
  lib/model.js
  lib/model/Capability.js
  lib/model/FineChannel.js
  lib/model/Fixture.js
  lib/model/Matrix.js
  package-lock.json
  package.json
  plugins/aglight/export.js
  plugins/color-chief/export.js
  plugins/d-light/export.js
  plugins/ecue/import.js
  plugins/gdtf/gdtf-attributes.js
  plugins/millumin/export.js
  plugins/op-z/export.js
  plugins/qlcplus_4.12.2/import.js
  plugins/qlcplus_4.12.2/presets.js
  server/webhook.js
  tests/dmx-value-scaling.js
  tests/external-links.js
  tests/fixture-valid.js
  tests/github/exports-valid.js
  tests/http-status.js
  ui/api/routes/fixtures/from-editor.js
  ui/api/routes/submit-feedback.js
  ui/components/CapabilityTypeIcon.vue
  ui/components/HelpWantedDialog.vue
  ui/components/PropertyInputEntity.vue
  ui/components/editor/EditorCapability.vue
  ui/components/editor/EditorMode.vue
  ui/components/fixture-page/FixturePageMatrix.vue
  ui/pages/rdm.vue
Labels: refactoring

#2252 Fix some links
  docs/CONTRIBUTING.md
  docs/fixture-model.md
  fixtures/abstract/twister-4.json
  fixtures/coemar/prospot-250-lx.json
  fixtures/elation/sixpar-300-ip.json
  fixtures/eurolite/led-fe-1500.json
  fixtures/evolight/colours-archspot-54-rgb.json
  fixtures/fractal-lights/par-led-7x10w.json
  fixtures/fractal-lights/par-led-7x12w.json
  fixtures/fractal-lights/par-led-7x9w.json
  fixtures/ledj/slimline-12q5-rgbw.json
  fixtures/lightmaxx/led-nano-par.json
  fixtures/manufacturers.json
  fixtures/mark/mbar-381-ip.json
  fixtures/mark/superbat-led-72.json
  fixtures/orion/orcan2.json
  tests/external-links.js
Labels: component-fixture

#2263 Fix 'stage-right/stage-wash-7x10w-led-moving-head' capability
  fixtures/stage-right/stage-wash-7x10w-led-moving-head.json
Labels: bug, component-fixture

#2266 Update and improve Stylelint
  .stylelintrc.json
  .stylelintrc.yaml
  nuxt.config.js
  package-lock.json
  package.json
  ui/assets/styles/fonts.scss
  ui/assets/styles/global.scss
  ui/assets/styles/mixins.scss
  ui/assets/styles/style.scss
  ui/assets/styles/theming.scss
  ui/assets/styles/vars.scss
  ui/components/A11yDialog.vue
  ui/components/CategoryBadge.vue
  ui/components/ClimateStrikeBanner.vue
  ui/components/ConditionalDetails.vue
  ui/components/DownloadButton.vue
  ui/components/HeaderBar.vue
  ui/components/HelpWantedMessage.vue
  ui/components/LabeledValue.vue
  ui/components/PropertyInputEntity.vue
  ui/components/editor/EditorCapability.vue
  ui/components/editor/EditorCapabilityWizard.vue
  ui/components/editor/EditorChannelDialog.vue
  ui/components/editor/EditorLink.vue
  ui/components/editor/EditorMode.vue
  ui/components/editor/EditorProportionalPropertySwitcher.vue
  ui/components/editor/EditorSubmitDialog.vue
  ui/components/fixture-page/FixturePage.vue
  ui/components/fixture-page/FixturePageCapabilityTable.vue
  ui/components/fixture-page/FixturePageChannel.vue
  ui/components/fixture-page/FixturePageMatrix.vue
  ui/components/fixture-page/FixturePageMode.vue
  ui/components/fixture-page/FixturePagePhysical.vue
  ui/components/fixture-page/FixturePageWheel.vue
  ui/components/global/OflSvg.vue
  ui/layouts/default.vue
  ui/pages/_manufacturerKey/_fixtureKey.vue
  ui/pages/about/plugins/_plugin.vue
Labels: dependencies, refactoring

#2271 Lint styles
  .stylelintrc.yaml
  ui/assets/styles/vars.scss
  ui/components/DownloadButton.vue
  ui/components/FixtureHeader.vue
  ui/components/PropertyInputEntity.vue
  ui/components/editor/EditorChannelDialog.vue
  ui/components/editor/EditorSubmitDialog.vue
  ui/components/fixture-page/FixturePageChannel.vue
  ui/pages/_manufacturerKey/_fixtureKey.vue
  ui/pages/index.vue
Labels: component-ui, refactoring
